version: '3.8'

services:
  backend:
    build: ./backend
    container_name: location-estimation-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./Competition Release:/app/Competition Release
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    restart: always

  frontend:
    build: ./frontend
    container_name: location-estimation-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always 