services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: location-estimation-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - "./Competition Release:/app/Competition_Release"  # Using underscore to avoid space issues
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: location-estimation-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always 